global:
  scrape_interval: 10s
  external_labels:
    system: quarkus-tracing

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: service-a
    metrics_path: /q/metrics
    honor_labels: true
    static_configs:
      - targets: [ 'service-a:8080' ]
        labels:
          app: service-a
          application: service-a
          system: quarkus-tracing

  - job_name: service-b
    metrics_path: /q/metrics
    honor_labels: true
    static_configs:
      - targets: [ 'service-b:8180' ]
        labels:
          app: service-b
          application: service-b
          system: quarkus-tracing

  - job_name: service-piada
    metrics_path: /q/metrics
    honor_labels: true
    static_configs:
      - targets: [ 'service-piadas:8280' ]
        labels:
          app: service-piada
          application: service-piada
          system: quarkus-tracing
